[package]
name = "eventsapis_proto"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.12.2"
prost-types = "0.11.9"
tonic = "0.9.2"

[build-dependencies]
prost-build = "0.11.9"
tonic-build = "0.9"

[lib]
path = "./src-rs/lib.rs"
